### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by klmansel** [UpstateWomenInSoftwareEngineering/study_helper#1]
We need a version of our `CONTRIBUTING.md` file for each UpWise Repo
Example from our WWCodeGreenville repo: https://github.com/klmansel/WWCodeGreenville/blob/master/CONTRIBUTING.md

**Comment by Psychodahlia** [comment]
Created a draft of a CONTRIBUTING.md file.

**Comment by JenBauer** [comment]
Hi @Psychodahlia, this is assigned to you now.  Please create a branch per the Readme steps.  Then, we can make a PR with your Markdown file and approve it for Hacktoberfest.
