### ISSUE TITLE
Add steps for using .env 

### ISSUE THREAD

**Issue by JenBauer** [UpstateWomenInSoftwareEngineering/study_helper#14]
A local .env file is needed to access the OpenAI API Key when running the app locally.  The steps for this need to be added to the readme.md file.

**Comment by mariannerv** [comment]
Hey, I would love to help!

**Comment by JenBauer** [comment]
Hi @mariannerv, thank you.  I've assigned you to this issue.  Please create a branch to get started per the Readme steps.

**Comment by mariannerv** [comment]
> Hi @mariannerv, thank you.  I've assigned you to this issue.  Please create a branch to get started per the Readme steps.

Thank you! I'll work on it as soon as I get back home :)

**Comment by mariannerv** [comment]
Hey @JenBauer ,  not sure if you've checked it already but I have submitted the PR with the changes to the README file. Cheers!
